apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  namespace: devops-tools
  labels:
    team: devops
    environment: dev
spec:
  storageClassName: jenkins-local-storage
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/jenkins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - w1-k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: local-storage-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
